### ISSUE TITLE
Suspicious permutation order

### ISSUE THREAD

**Issue by denkorzh** [ehoogeboom/multinomial_diffusion#1]
Hi! Thanks for sharing your code.

While working with your codebase I noticed that the permutation order in UNet seems to be incorrect unless you have a very specific data format.

https://github.com/ehoogeboom/multinomial_diffusion/blob/7fc4b6f1e1002417af5ad1bf01daa0089df7e740/segmentation_diffusion/layers/layers.py#L192

```python
B, C, H, W = x.size()
x = self.embedding(x)  # B x C x H x W x dim

x = x.permute(0, 1, 3, 2, 4)  # B x C x W x H x dim
x = x.reshape(B, C * self.dim, H, W)  # ???
```

**Comment by ehoogeboom** [comment]
Hi! Great catch! Indeed this makes the input to the model somewhat unnatural, thank you for notifying us. I will update the code accordingly. Also, I will re-run the experiment and report the difference in performance. From initial runs it seems to improve the performance of the model (to 0.305 test, on par with the flow-based models in the paper). Thanks again and all the best, Emiel
