### ISSUE TITLE
Not quite sure about some Eqs.

### ISSUE THREAD

**Issue by mhh0318** [ehoogeboom/multinomial_diffusion#4]
https://github.com/ehoogeboom/multinomial_diffusion/blob/66f17340e4cd200059bff228cf98a597bf084c26/diffusion_utils/diffusion_multinomial.py#L194

Thanks for the code sharing.. But may I know why p(x_t|x_tmin1) here call the function q_sample_timestep(x_t,t)?

Best.

**Comment by ehoogeboom** [comment]
Hi Michael,

It's computing Eq. 13 in the paper. It's not calling the q_sample_timestep though, it's calling q_pred_one_timestep (which returns a vector log probabilities). 

In the bottom line of Eq. 13 for tilde(theta) there are 2 terms divided by the element wise multiply. The first term corresponds to "self.q_pred_one_timestep(log_x_t, t)". The second term corresponds to this variable in the code named "log_EV_qxtmin_x0".

**Comment by mhh0318** [comment]
Hi Emiel,

Really thanks for your reply!

May I ask a slightly more detailed question?

1. 
the function `self.q_pred_one_timestep(log_x_t, t)` means  alpha_t * E[xt] + (1 - alpha_t) 1 / K. 
in Eq.11: q(x_t|xt_1) = alpha_t * xt_1 + (1 - alpha_t) 1 / K.      #(xt_1 means x_{t-1})
are they same?

2.
I think I misunderstand the eq.13. 
but is this following correct?
p(xt_1|x_t,x_0) = [ p(x_t|xt_1,x_0) p(xt_1|x_0) ] /  p(x_t|x_0)

where p(x_t|x_0) given by the function `q_pred(x_0, t)`,
p(xt_1|x_0) given `q_pred(x_0,t_1)` and p(x_t|xt_1,x_0) given by the `q_pred_one_timestep(xt_1, t)`?

**Comment by ehoogeboom** [comment]
Hi,

1. Indeed, even though the code was originally written to return a vector of probs for xt, given x_tmin1, it can also compute the term we desire from Eq. 13 where the vector of probs is for xt_min1. 

2. Yes, exactly. And instead of computing p(xt | x0) directly we just renormalize since it’s a constant w.r.t. xt_min1.

**Comment by mhh0318** [comment]
Noted! Thanks!
