### ISSUE TITLE
Question of the formula.13 in the paper and in the implementation.

### ISSUE THREAD

**Issue by guyuchao** [ehoogeboom/multinomial_diffusion#5]
The posterior q( x_{t-1} | x_t, x_0 ) can be formulated as following based on the Bayesian formula.  
![屏幕截图 2022-06-16 234032](https://user-images.githubusercontent.com/31696690/176663159-c11b821a-7fe4-4421-9706-dfd318775df9.png)

But in the paper, the formula.13 seems only contain the q( x_{t} | x{t-1} ) and q( x_{t-1} | x_0 ) in the numerator. Could you help me understand why you exclude the divison by q(x_t|x_0)?

![屏幕截图 2022-06-16 234032](https://user-images.githubusercontent.com/31696690/176662458-6012f929-cd08-4279-9ec0-508a5d0de06b.png)

**Comment by ehoogeboom** [comment]
Hi,

You’re on the right track. Two observations will bring you to Eq. 13:

1. the process is markov so q( x_{t} | x{t-1}, x_{0}) = q( x_{t} | x{t-1} )
2. The denominator is constant wrt x_{t-1}. So dividing by that term is equivalent to renormalizing

Hope that helps, best

**Comment by guyuchao** [comment]
Thanks for your reply. I know the 1). But for 2), I still have some questions. tbe denominator may have different constant scale factors wrt.  different category {k \in K}. This may further influence the normalized distribution. Even the constant scale is the same for different k, it may also influence the normalized distribution (similar to the temperature).

**Comment by ehoogeboom** [comment]
Hmm I don’t think I understand entirely what you mean by that. “Different values k in K” for which variable?

**Comment by guyuchao** [comment]
> Hmm I don’t think I understand entirely what you mean by that. “Different values k in K” for which variable?

Sorry. K means category. My question is whether the denominator will change the value of different categories, then influence the normalized distribution. (If you divide by a temperature before softmax and then it will make the softmax-normalized distribution more sharp or smooth.)

**Comment by ehoogeboom** [comment]
Hmm still not entirely sure but here’s a try: 
First of all, temperature (multiplication inside the exp) and normalization (multiplication outside the exp) are two different things. 

Further, the way you normalize, is you get the probs that x_{t-1} = k, for all k, and then sum them together. This sum is equal (and I verified this when I was programming it) to q(xt | x0).

**Comment by guyuchao** [comment]
Thanks for your help. My problem is solved.

**Comment by guyuchao** [comment]
By the way, in the code `log_EV_qxtmin_x0 = self.q_pred(log_x_start, t_minus_1)`, what the exact meaning of the abbreviation 'EV' and 'min' (log_EV_qxtmin_x0). 'min' may means minus1?

**Comment by ehoogeboom** [comment]
EV stands for expected value, on the “min” you’re correct. See also this thread on that piece of code https://github.com/ehoogeboom/multinomial_diffusion/issues/4

**Comment by guyujun** [comment]
> Hi,
> 
> You’re on the right track. Two observations will bring you to Eq. 13:
> 
> 1. the process is markov so q( x_{t} | x{t-1}, x_{0}) = q( x_{t} | x{t-1} )
> 2. The denominator is constant wrt x_{t-1}. So dividing by that term is equivalent to renormalizing
> 
> Hope that helps, best

q( x_{t} | x{t-1}, x0) should be = a_{t}x_{t-1} + (1-a_{t})/K), why you here use x_{t}? condition is given x{t-1}.

**Comment by QWTforGithub** [comment]
> > Hi,
> > You’re on the right track. Two observations will bring you to Eq. 13:
> > 
> > 1. the process is markov so q( x_{t} | x{t-1}, x_{0}) = q( x_{t} | x{t-1} )
> > 2. The denominator is constant wrt x_{t-1}. So dividing by that term is equivalent to renormalizing
> > 
> > Hope that helps, best
> 
> q( x_{t} | x{t-1}, x0) should be = a_{t}x_{t-1} + (1-a_{t})/K), why you here use x_{t}? condition is given x{t-1}.

Because the result of this definition is xt.
