### ISSUE TITLE
Question about q_posterior.

### ISSUE THREAD

**Issue by guyuchao** [ehoogeboom/multinomial_diffusion#6]
Although you have noticed us that we can use x_t instead of x_tmin1, I have trouble understanding why it can hold.
 `# unnormed_logprobs = log_EV_qxtmin_x0 + log q_pred_one_timestep(x_t, t)`
 `# Note: _NOT_ x_tmin1, which is how the formula is typically used!!!`

Instead, I want to to follow the original formula that first sample x_tmin1 based on x0, then use this to compute q(xt|x_{t-1}). Is the following code correct? And have you tried experiment with the original formula? 
`log_x_tmin = self.log_sample_categorical(log_EV_qxtmin_x0)`
`unnormed_logprobs = log_EV_qxtmin1_x0 + self.q_pred_one_timestep(log_x_tmin, t)`

**Comment by ehoogeboom** [comment]
The comment in the code there is a bit confusing, I'll remove that. 

Your last suggestion though is to sample x_tmin1, that is doing something different. In the original formula's we don't want to sample, we want to compute the posterior closed-form.

**Comment by guyuchao** [comment]
Great thanks.
