### ISSUE TITLE
Computing decoder NLL in multinomial diffusion

### ISSUE THREAD

**Issue by LZhengisme** [ehoogeboom/multinomial_diffusion#7]
Hi, thanks for sharing the code!

I think there is a mismatch in computing $\log p(x_0|x_1)$ (i.e., the decoder log likelihood) between the code and the paper. 
- In the paper, Eq. (14) shows that it is simply defined as $p(x_0 | x_1) = \widehat{x}_0$, 
- while the code snippet below actually computes $p(x_0 | x_1) \propto \widehat{x}_0 \odot (x_1\alpha_1 + (1 − \alpha_1)/K)$, which is an approximate posterior $\theta\_{\text{post}}(x_1, \widehat{x}_0) \propto q(x_1 | x_0) \widehat{x}_0$.

https://github.com/ehoogeboom/multinomial_diffusion/blob/9d907a60536ad793efd6d2a6067b3c3d6ba9fce7/diffusion_utils/diffusion_multinomial.py#L187

If the mismatch was the case, this just leads to a different parameterization strategy for modeling the decoder and a possible fix to match the computation in the paper might be simply reversing L182 and L187 (with variables changed correspondingly):

```python
####################### ORIGINAL L182-187 ####################################
log_EV_qxtmin_x0 = torch.where(t_broadcast == 0, log_x_start, log_EV_qxtmin_x0)


# Note: _NOT_ x_tmin1, which is how the formula is typically used!!!
# Not very easy to see why this is true. But it is :)
unnormed_logprobs = log_EV_qxtmin_x0 + self.q_pred_one_timestep(log_x_t, t)
##############################################################################

#########################      FIXED      ####################################
unnormed_logprobs = log_EV_qxtmin_x0 + self.q_pred_one_timestep(log_x_t, t)


# Note: _NOT_ x_tmin1, which is how the formula is typically used!!!
# Not very easy to see why this is true. But it is :)
unnormed_logprobs = torch.where(t_broadcast == 0, log_x_start, unnormed_logprobs)
##############################################################################
```
I might have missed something and please let me know if so! xD

**Comment by ehoogeboom** [comment]
Hi, great catch this is not desired behaviour. Indeed the code now computes P(x0 | x1) proportional to what you write. 

The good news (for me ;) ) is that if alpha_1 / sigma_1 are very close to 1 and 0, it is hopefully not too much of an issue. Also if the model is completely certain, it drowns out the effect of q(x1 | x0) completely. 

Thanks for reaching out and really impressed you even found this bug :)

**Comment by LZhengisme** [comment]
Thanks for your prompt reply! Your reasoning makes a lot of sense to me ;)
